/*
	(C)2004 TriMoon Inc.
	Author: Tri_Moon <tripple_moon_3m@yahoo.com>
	Solar System.
	Items: Mace

	Contributed by:
	2005/01/21	TriMoon (Initial-data and awk script)
	2005/01/21	Liz&Cap (Dev.team item-info)
	2005/01/23	Auto-Generated using GNU awk
	2005/01/23	TriMoon (Hand Edited)

	This work is licensed under a Creative Commons License !
	See: http://creativecommons.org/licenses/by-nc-nd/2.0/
*/
/***************************************************************************
				Exception handling.
***************************************************************************/
try{
/***************************************************************************
				Fill ItemTypes
***************************************************************************/
	//	ItemType(nLevel, sName, sType, sSubType, sUseage, nAtk, nWeight, nValue, bStack, nMax, bDrop, sStrong, sWeak, sDesc, sRace)

	/*	Templates for easy adding
	Items.add( new ItemType(0, "", "Weapon", "Mace", "Any Hand", 0.0, 0.00, 0.00, false, 5, true, "Bluntness", null, "") );
	*/
	Items.add( new ItemType(1, "Old Mace", "Weapon", "Mace", "Any Hand", 1.6, 0.70, 250.00, false, 5, true, "Bluntness", null, "This dual-handed newbie weapon will add 2.5 to your attack.") );
	Items.add( new ItemType(8, "Greater Old Mace", "Weapon", "Mace", "Any Hand", 7.2, 0.70, 125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(16, "Superior Old Mace", "Weapon", "Mace", "Any Hand", 13.5, 0.70, 125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(5, "Brass Mace", "Weapon", "Mace", "Any Hand", 4.1, 0.70, 1250.00, false, 5, true, "Bluntness", null, "This dual-handed mace adds 12.5 to your attack.") );
	Items.add( new ItemType(13, "Greater Brass Mace", "Weapon", "Mace", "Any Hand", 10.4, 0.70, 625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(21, "Superior Old Mace", "Weapon", "Mace", "Any Hand", 16.6, 0.70, 625.00, false, 5, true, "Bluntness", null, "This dual-handed newbie weapon.") );
	Items.add( new ItemType(10, "Iron Mace", "Weapon", "Mace", "Any Hand", 7.2, 0.90, 2500.00, false, 5, true, "Bluntness", null, "This dual-handed mace will crush your enemy's skull with additional 25 attack.") );
	Items.add( new ItemType(18, "Greater Iron Mace", "Weapon", "Mace", "Any Hand", 13.5, 0.90, 1250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(26, "Superior Iron Mace", "Weapon", "Mace", "Any Hand", 19.8, 0.90, 1250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(15, "Orcen Mace", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 3750.00, false, 5, true, "Bluntness", null, "This weapon inflicts damage to your enemy.") );
	Items.add( new ItemType(23, "Greater Orcen Mace", "Weapon", "Mace", "Any Hand", 16.6, 0.90, 1875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(31, "Superior Orcen Mace", "Weapon", "Mace", "Any Hand", 22.9, 0.90, 1875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(18, "Orcen Mace of Lesser Fire", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness,Fire", null, "") );
	Items.add( new ItemType(18, "Orcen Mace of Lesser Ice", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness,Ice", null, "") );
	Items.add( new ItemType(18, "Orcen Mace of Lesser Energy", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness,Energy", null, "") );
	Items.add( new ItemType(18, "Orcen Mace of Lesser Water", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness,Water", null, "") );
	Items.add( new ItemType(18, "Orcen Mace Lesser Wind", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness,Wind", null, "") );
	Items.add( new ItemType(21, "Orcen Mace of Fire", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness,Fire", null, "") );
	Items.add( new ItemType(21, "Orcen Mace of Ice", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness,Ice", null, "") );
	Items.add( new ItemType(21, "Orcen Mace of Energy", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness,Energy", null, "") );
	Items.add( new ItemType(21, "Orcen Mace of Water", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness,Water", null, "") );
	Items.add( new ItemType(21, "Orcen Mace of Wind", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness,Wind", null, "") );
	Items.add( new ItemType(24, "Orcen Mace of Speed", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(24, "Orcen Mace of Defense", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(24, "Orcen Mace of Jumping", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(15, "Cursed Orcen Mace of Greater Water", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness,Water", null, "") );
	Items.add( new ItemType(15, "Cursed Orcen Mace of Greater Wind", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness,Wind", null, "") );
	Items.add( new ItemType(15, "Cursed Orcen Mace of Greater Energy", "Weapon", "Mace", "Any Hand", 10.4, 0.90, 1875.00, false, 5, true, "Bluntness,Energy", null, "-5AC") );
	Items.add( new ItemType(20, "Pain Maker", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 5000.00, false, 5, true, "Piercing,Bluntness", null, "A simple spiked mace, you say, but it's effects on your enemy will not feel simple to them.") );
	Items.add( new ItemType(28, "Greater Pain Maker", "Weapon", "Mace", "Any Hand", 19.8, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness", null, "") );
	Items.add( new ItemType(36, "Superior Pain Maker", "Weapon", "Mace", "Any Hand", 100.0, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness", null, "") );
	Items.add( new ItemType(23, "Pain Maker of Lesser Earth", "Weapon", "Mace", "Any Hand", 26.0, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness,Earth", null, "") );
	Items.add( new ItemType(23, "Pain Maker of Lesser Light", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness,Light", null, "") );
	Items.add( new ItemType(23, "Pain Maker of Lesser Poison", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness,Poison", null, "") );
	Items.add( new ItemType(23, "Pain Maker of Lesser Acid", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness,Acid", null, "") );
	Items.add( new ItemType(23, "Pain Maker of Lesser Magical", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness,Magical", null, "") );
	Items.add( new ItemType(23, "Pain Maker of Lesser Darkness", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness,Darkness", null, "") );
	Items.add( new ItemType(26, "Pain Maker of Earth", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness,Earth", null, "") );
	Items.add( new ItemType(26, "Pain Maker of Light", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness,Light", null, "") );
	Items.add( new ItemType(26, "Pain Maker of Poison", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness,Poison", null, "") );
	Items.add( new ItemType(26, "Pain Maker of Acid", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness,Acid", null, "") );
	Items.add( new ItemType(26, "Pain Maker of Magical", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness,Magical", null, "") );
	Items.add( new ItemType(26, "Pain Maker of Darkness", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness,Darkness", null, "") );
	Items.add( new ItemType(29, "Pain Maker of Strength", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness", null, "") );
	Items.add( new ItemType(29, "Pain Maker of Health Regen", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness", null, "") );
	Items.add( new ItemType(29, "Pain Maker of Health", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness", null, "") );
	Items.add( new ItemType(20, "Cursed Pain Maker of Greater Earth", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness,Earth", null, "") );
	Items.add( new ItemType(20, "Cursed Pain Maker of Greater Acid", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness,Acid", null, "") );
	Items.add( new ItemType(20, "Cursed Pain Maker of Greater Poison", "Weapon", "Mace", "Any Hand", 13.5, 1.10, 2500.00, false, 5, true, "Piercing,Bluntness,Poison", null, "") );
	Items.add( new ItemType(25, "Worn Scepter", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 6250.00, false, 5, true, "Bluntness,Sharpness,Piercing", null, "") );
	Items.add( new ItemType(33, "Greater Worn Scepter", "Weapon", "Mace", "Any Hand", 22.9, 1.10, 3125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(41, "Superior Worn Scepter", "Weapon", "Mace", "Any Hand", 29.1, 1.10, 3125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(28, "Worn Scepter of Lesser Fire", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness,Fire", null, "") );
	Items.add( new ItemType(28, "Worn Scepter of Lesser Ice", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness,Ice", null, "") );
	Items.add( new ItemType(28, "Worn Scepter of Lesser Energy", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness,Energy", null, "") );
	Items.add( new ItemType(28, "Worn Scepter of Lesser Water", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness,Water", null, "") );
	Items.add( new ItemType(28, "Worn Scepter of Lesser Wind", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness,Wind", null, "") );
	Items.add( new ItemType(31, "Worn Scepter of Fire", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness,Fire", null, "") );
	Items.add( new ItemType(31, "Worn Scepter of Ice", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness,Ice", null, "") );
	Items.add( new ItemType(31, "Worn Scepter of Energy", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness,Energy", null, "") );
	Items.add( new ItemType(31, "Worn Scepter of Water", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness,Water", null, "") );
	Items.add( new ItemType(31, "Worn Scepter of Wind", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness,Wind", null, "") );
	Items.add( new ItemType(33, "Worn Scepter of Speed", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(33, "Worn Scepter of Defense", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(33, "Worn Scepter of Jumping", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(25, "Cursed Worn Scepter of Greater Fire", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness,Fire", null, "") );
	Items.add( new ItemType(25, "Cursed Worn Scepter of Greater Ice", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness,Ice", null, "") );
	Items.add( new ItemType(25, "Cursed Worn Scepter of Superior Fire", "Weapon", "Mace", "Any Hand", 16.6, 1.10, 3125.00, false, 5, true, "Bluntness,Fire", null, "") );
	Items.add( new ItemType(30, "Decorative Brass Mace", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(38, "Greater Decorative Brass Mace", "Weapon", "Mace", "Any Hand", 26.0, 1.30, 3750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(46, "Superior Decorative Brass Mace", "Weapon", "Mace", "Any Hand", 32.2, 1.30, 3750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(33, "Decorative Brass Mace of Lesser Earth", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness,Earth", null, "") );
	Items.add( new ItemType(33, "Decorative Brass Mace of Lesser Light", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness,Light", null, "") );
	Items.add( new ItemType(33, "Decorative Brass Mace of Lesser Poison", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness,Poison", null, "") );
	Items.add( new ItemType(33, "Decorative Brass Mace of Lesser Acid", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness,Acid", null, "") );
	Items.add( new ItemType(33, "Decorative Brass Mace of Lesser Magical", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness,Magical", null, "") );
	Items.add( new ItemType(33, "Decorative Brass Mace of Lesser Darkness", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness,Darkness", null, "") );
	Items.add( new ItemType(36, "Decorative Brass Mace of Earth", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness,Earth", null, "") );
	Items.add( new ItemType(36, "Decorative Brass Mace of Light", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness,Light", null, "") );
	Items.add( new ItemType(36, "Decorative Brass Mace of Poison", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness,Poison", null, "") );
	Items.add( new ItemType(36, "Decorative Brass Mace of Acid", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness,Acid", null, "") );
	Items.add( new ItemType(36, "Decorative Brass Mace of Magical", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness,Magical", null, "") );
	Items.add( new ItemType(36, "Decorative Brass Mace of Darkness", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness,Darkness", null, "") );
	Items.add( new ItemType(38, "Decorative Brass Mace of Strength", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(38, "Decorative Brass Mace of Health", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(38, "Decorative Brass Mace of Health Regen", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(30, "Cursed Decorative Brass Mace of Greater Light", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness,Light", null, "") );
	Items.add( new ItemType(30, "Cursed Decorative Brass Mace of Greater Darkness", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness,Darkness", null, "") );
	Items.add( new ItemType(30, "Cursed Decorative Brass Mace of Greater Magical", "Weapon", "Mace", "Any Hand", 19.8, 1.30, 3750.00, false, 5, true, "Bluntness,Magical", null, "") );
	Items.add( new ItemType(35, "Brass Scepter", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(43, "Greater Brass Scepter", "Weapon", "Mace", "Any Hand", 29.1, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(51, "Superior Brass Scepter", "Weapon", "Mace", "Any Hand", 32.2, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(38, "Brass Scepter of Lesser Poison added", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(38, "Brass Scepter of Lesser Fire", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(38, "Brass Scepter of Lesser Ice", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(38, "Brass Scepter of Lesser Energy", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(38, "Brass Scepter of Lesser Water", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(38, "Brass Scepter of Lesser Wind", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(41, "Brass Scepter of Fire", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(41, "Brass Scepter of Ice", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(41, "Brass Scepter of Energy", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(41, "Brass Scepter of Water", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(41, "Brass Scepter of Wind", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(38, "Brass Scepter of Speed", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(38, "Brass Scepter of Defense", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(38, "Brass Scepter of Jumping", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(35, "Cursed Brass Scepter of Greater Fire", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(35, "Cursed Brass Scepter of Greater Ice", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(35, "Cursed Brass Scepter of Superior Fire", "Weapon", "Mace", "Any Hand", 22.9, 1.30, 4375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(40, "Rusted Basher", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 10000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(48, "Greater Rusted Basher Mace", "Weapon", "Mace", "Any Hand", 32.2, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(56, "Superior Rusted Basher Mace", "Weapon", "Mace", "Any Hand", 38.5, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(43, "Rusted Basher Mace of Lesser Earth", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(43, "Rusted Basher Mace of Lesser Light", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(43, "Rusted Basher Mace of Lesser Poison", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(43, "Rusted Basher Mace of Lesser Acid", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(43, "Rusted Basher Mace of Lesser Magical", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(43, "Rusted Basher Mace of Lesser Darkness", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(46, "Rusted Basher Mace of Earth", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(46, "Rusted Basher Mace of Light", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(46, "Rusted Basher Mace of Poison", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(46, "Rusted Basher Mace of Acid", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(46, "Rusted Basher Mace of Magical", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(46, "Rusted Basher Mace of Darkness", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(43, "Rusted Basher Mace of Strength", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(43, "Rusted Basher Mace of Health", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(43, "Rusted Basher Mace of Health Regen", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(40, "Cursed Rusted Basher Mace of Greater Light", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(40, "Cursed Rusted Basher Mace of Greater Darkness", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(40, "Cursed Rusted Basher Mace of Greater Magical", "Weapon", "Mace", "Any Hand", 26.0, 1.50, 5000.00, false, 5, true, "Bluntness,Piercing,Sharpness", null, "") );
	Items.add( new ItemType(45, "Decrorative Iron Mace", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(53, "Greater Decorative Iron Mace", "Weapon", "Mace", "Any Hand", 35.4, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(61, "Superior Decorative Iron Mace", "Weapon", "Mace", "Any Hand", 41.6, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(48, "Decorative Iron Mace of Lesser Fire", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(48, "Decorative Iron Mace of Lesser Ice", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(48, "Decorative Iron Mace of Lesser Energy", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(48, "Decorative Iron Mace of Lesser Water", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(48, "Decorative Iron Mace of Lesser Wind", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(51, "Decorative Iron Mace of Fire", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(51, "Decorative Iron Mace of Ice", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(51, "Decorative Iron Mace of Energy", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(51, "Decorative Iron Mace of Water", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(51, "Decorative Iron Mace of Wind", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(48, "Decorative Iron Mace of Speed", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(48, "Decorative Iron Mace of Defense", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(48, "Decorative Iron Mace of Jumping", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(45, "Cursed Decorative Iron Mace of Greater Fire", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(45, "Cursed Decorative Iron Mace of Greater Ice", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(45, "Cursed Decorative Iron Mace of Superior Fire", "Weapon", "Mace", "Any Hand", 29.1, 1.50, 5625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(50, "Iron Scepter", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(58, "Greater Iron Scepter", "Weapon", "Mace", "Any Hand", 38.5, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(66, "Superior Iron Scepter", "Weapon", "Mace", "Any Hand", 44.8, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(53, "Iron Scepter of Lesser Earth", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(53, "Iron Scepter of Lesser Light", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(53, "Iron Scepter of Lesser Poison", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(53, "Iron Scepter of Lesser Acid", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(53, "Iron Scepter of Lesser Magical", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(53, "Iron Scepter of Lesser Darkness", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(56, "Iron Scepter of Earth", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(56, "Iron Scepter of Light", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(56, "Iron Scepter of Poison", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(56, "Iron Scepter of Acid", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(56, "Iron Scepter of Magical", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(56, "Iron Scepter of Darkness", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(53, "Iron Scepter of Strength", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(53, "Iron Scepter of Health", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(53, "Iron Scepter of Health Regen", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(50, "Cursed Iron Scepter of Greater Light", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(50, "Cursed Iron Scepter of Greater Darkness", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(50, "Cursed Iron Scepter of Greater Magical", "Weapon", "Mace", "Any Hand", 32.2, 1.70, 6250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(55, "Basher", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 13750.00, false, 5, true, "Bluntness,Sharpness,Piercing", null, "") );
	Items.add( new ItemType(63, "Greater Basher", "Weapon", "Mace", "Any Hand", 41.6, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(71, "Superior Basher", "Weapon", "Mace", "Any Hand", 47.9, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(58, "Basher of Lesser Fire", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(58, "Basher of Lesser Ice", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(58, "Basher of Lesser Energy", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(58, "Basher of Lesser Water", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(58, "Basher of Lesser Wind", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(61, "Basher of Fire", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(61, "Basher of Ice", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(61, "Basher of Energy", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(61, "Basher of Water", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(61, "Basher of Wind", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(58, "Basher of Speed", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(58, "Basher of Defense", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(58, "Basher of Jumping", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(55, "Cursed Basher of Greater Fire", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(55, "Cursed Basher of Greater Ice", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(55, "Cursed Basher of Superior Fire", "Weapon", "Mace", "Any Hand", 35.4, 1.70, 6875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(60, "Fighters Mace", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 15000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(68, "Greater Fighter Mace", "Weapon", "Mace", "Any Hand", 44.8, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(76, "Superior Fighter Mace", "Weapon", "Mace", "Any Hand", 51.0, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(63, "Fighter Mace of Lesser Earth", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(63, "Fighter Mace of Lesser Light", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(63, "Fighter Mace of Lesser Poison", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(63, "Fighter Mace of Lesser Acid", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(63, "Fighter Mace of Lesser Magical", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(63, "Fighter Mace of Lesser Darkness", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(66, "Fighter Mace of Earth", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(66, "Fighter Mace of Light", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(66, "Fighter Mace of Poison", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(66, "Fighter Mace of Acid", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(66, "Fighter Mace of Magical", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(66, "Fighter Mace of Darkness", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(63, "Fighter Mace of Strength", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(63, "Fighter Mace of Health", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(63, "Fighter Mace of Health Regen", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(60, "Cursed Fighter Mace of Greater Light", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(60, "Cursed Fighter Mace of Greater Darkness", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(60, "Cursed Fighter Mace of Greater Magical", "Weapon", "Mace", "Any Hand", 38.5, 1.90, 7500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(65, "Elite Brass Scepter", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 16250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(73, "Greater Elite Brass Scepter", "Weapon", "Mace", "Any Hand", 47.9, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(81, "Superior Elite Brass Scepter", "Weapon", "Mace", "Any Hand", 54.1, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(68, "Elite Brass Scepter of Lesser Fire", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(68, "Elite Brass Scepter of Lesser Ice", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(68, "Elite Brass Scepter of Lesser Energy", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(68, "Elite Brass Scepter of Lesser Water", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(68, "Elite Brass Scepter of Lesser Wind", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(71, "Elite Brass Scepter of Fire", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(71, "Elite Brass Scepter of Ice", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(71, "Elite Brass Scepter of Energy", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(71, "Elite Brass Scepter of Water", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(71, "Elite Brass Scepter of Wind", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(68, "Elite Brass Scepter of Speed", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(68, "Elite Brass Scepter of Defense", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(68, "Elite Brass Scepter of Jumping", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(65, "Cursed Elite Brass Scepter of Greater Fire", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(65, "Cursed Elite Brass Scepter of Greater Ice", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(65, "Cursed Elite Brass Scepter of Superior Fire", "Weapon", "Mace", "Any Hand", 41.6, 1.90, 8125.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(70, "Reinforced Brass Mace", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 17500.00, false, 5, true, "Bluntness,Piercing", null, "") );
	Items.add( new ItemType(78, "Greater Reinforced Brass Mace", "Weapon", "Mace", "Any Hand", 51.0, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(86, "Superior Reinforced Brass Mace", "Weapon", "Mace", "Any Hand", 57.2, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(73, "Reinforced Brass Mace of Lesser Earth", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(73, "Reinforced Brass Mace of Lesser Light", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(73, "Reinforced Brass Mace of Lesser Poison", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(73, "Reinforced Brass Mace of Lesser Acid", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(73, "Reinforced Brass Mace of Lesser Magical", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(73, "Reinforced Brass Mace of Lesser Darkness", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(76, "Reinforced Brass Mace of Earth", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(76, "Reinforced Brass Mace of Light", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(76, "Reinforced Brass Mace of Poison", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(76, "Reinforced Brass Mace of Acid", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(76, "Reinforced Brass Mace of Magical", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(76, "Reinforced Brass Mace of Darkness", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(73, "Reinforced Brass Mace of Strength", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(73, "Reinforced Brass Mace of Health", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(73, "Reinforced Brass Mace of Health Regen", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(70, "Cursed Reinforced Brass Mace of Greater Light", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(70, "Cursed Reinforced Brass Mace of Greater Darkness", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(70, "Cursed Reinforced Brass Mace of Greater Magical", "Weapon", "Mace", "Any Hand", 44.8, 2.10, 8750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(75, "Combat  Mace", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 18750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(83, "Greater Combat Mace", "Weapon", "Mace", "Any Hand", 54.1, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(91, "Superior Combat Mace", "Weapon", "Mace", "Any Hand", 60.4, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(78, "Combat Mace of Lesser Fire", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(78, "Combat Mace of Lesser Ice", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(78, "Combat Mace of Lesser Energy", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(78, "Combat Mace of Lesser Water", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(78, "Combat Mace of Lesser Wind", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(81, "Combat Mace of Fire", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(81, "Combat Mace of Ice", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(81, "Combat Mace of Energy", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(81, "Combat Mace of Water", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(81, "Combat Mace of Wind", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(78, "Combat Mace of Speed", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(78, "Combat Mace of Defense", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(78, "Combat Mace of Jumping", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(75, "Cursed Combat Mace of Greater Fire", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(75, "Cursed Combat Mace of Greater Ice", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(75, "Cursed Combat Mace of Superior Fire", "Weapon", "Mace", "Any Hand", 47.9, 2.10, 9375.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(80, "Emerald Mace", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 20000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(88, "Greater Emerald Mace", "Weapon", "Mace", "Any Hand", 57.2, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(96, "Superior Emerald Mace", "Weapon", "Mace", "Any Hand", 63.5, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(83, "Emerald Mace of Lesser Earth", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(83, "Emerald Mace of Lesser Light", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(83, "Emerald Mace of Lesser Poison", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(83, "Emerald Mace of Lesser Acid", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(83, "Emerald Mace of Lesser Magical", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(83, "Emerald Mace of Lesser Darkness", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(86, "Emerald Mace of Earth", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(86, "Emerald Mace of Light", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(86, "Emerald Mace of Poison", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(86, "Emerald Mace of Acid", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(86, "Emerald Mace of Magical", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(86, "Emerald Mace of Darkness", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(83, "Emerald Mace of Strength", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(83, "Emerald Mace of Health", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(83, "Emerald Mace of Health Regen", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(80, "Cursed Emerald Mace of Greater Light", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(80, "Cursed Emerald Mace of Greater Darkness", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(80, "Cursed Emerald Mace of Greater Magical", "Weapon", "Mace", "Any Hand", 51.0, 2.30, 10000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(85, "Assassins Mace", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 21250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(93, "Greater Assassins Mace", "Weapon", "Mace", "Any Hand", 60.4, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(101, "Superior Assassins Mace", "Weapon", "Mace", "Any Hand", 66.6, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(88, "Assassins Mace of Lesser Fire", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(88, "Assassins Mace of Lesser Ice", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(88, "Assassins Mace of Lesser Energy", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(88, "Assassins Mace of Lesser Water", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(88, "Assassins Mace of Lesser Wind", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(91, "Assassins Mace of Fire", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(91, "Assassins Mace of Ice", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(91, "Assassins Mace of Energy", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(91, "Assassins Mace of Water", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(91, "Assassins Mace of Wind", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(88, "Assassins Mace of Speed", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(88, "Assassins Mace of Defense", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(88, "Assassins Mace of Jumping", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(85, "Cursed Assassins Mace of Greater Fire", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(85, "Cursed Assassins Mace of Greater Ice", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(85, "Cursed Assassins Mace of Superior Fire", "Weapon", "Mace", "Any Hand", 54.1, 2.30, 10625.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(90, "Soldiers Mace", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 22500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(98, "Greater Soldiers Mace", "Weapon", "Mace", "Any Hand", 63.5, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(106, "Superior Soldiers Mace", "Weapon", "Mace", "Any Hand", 69.8, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(93, "Soldiers Mace of Lesser Earth", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(93, "Soldiers Mace of Lesser Light", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(93, "Soldiers Mace of Lesser Poison", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(93, "Soldiers Mace of Lesser Acid", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(93, "Soldiers Mace of Lesser Magical", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(93, "Soldiers Mace of Lesser Darkness", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(96, "Soldiers Mace of Earth", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(96, "Soldiers Mace of Light", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(96, "Soldiers Mace of Poison", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(96, "Soldiers Mace of Acid", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(96, "Soldiers Mace of Magical", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(96, "Soldiers Mace of Darkness", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(93, "Soldiers Mace of Strength", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(93, "Soldiers Mace of Health", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(93, "Soldiers Mace of Health Regen", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(90, "Cursed Soldiers Mace of Greater Light", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(90, "Cursed Soldiers Mace of Greater Darkness", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(90, "Cursed Soldiers Mace of Greater Magical", "Weapon", "Mace", "Any Hand", 57.2, 2.50, 11250.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(95, "War Mace", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 23750.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(103, "Greater War Mace", "Weapon", "Mace", "Any Hand", 66.6, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(111, "Superior War Mace", "Weapon", "Mace", "Any Hand", 72.9, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(98, "War Mace of Lesser Fire", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(98, "War Mace of Lesser Ice", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(98, "War Mace of Lesser Energy", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(98, "War Mace of Lesser Water", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(98, "War Mace of Lesser Wind", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(101, "War Mace of Fire", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(101, "War Mace of Ice", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(101, "War Mace of Energy", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(101, "War Mace of Water", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(101, "War Mace of Wind", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(98, "War Mace of Speed", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(98, "War Mace of Defense", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(98, "War Mace of Jumping", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(95, "Cursed War Mace of Greater Fire", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(95, "Cursed War Mace of Greater Ice", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(95, "Cursed War Mace of Superior Fire", "Weapon", "Mace", "Any Hand", 60.4, 2.50, 11875.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(100, "Royal Mace", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 25000.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(108, "Greater Royal Mace", "Weapon", "Mace", "Any Hand", 69.8, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(116, "Superior Royal Mace", "Weapon", "Mace", "Any Hand", 76.0, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(103, "Royal Mace of Lesser Earth", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(103, "Royal Mace of Lesser Light", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(103, "Royal Mace of Lesser Poison", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(103, "Royal Mace of Lesser Acid", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(103, "Royal Mace of Lesser Magical", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(103, "Royal Mace of Lesser Darkness", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(106, "Royal Mace of Earth", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(106, "Royal Mace of Light", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(106, "Royal Mace of Poison", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(106, "Royal Mace of Acid", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(106, "Royal Mace of Magical", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(106, "Royal Mace of Darkness", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(103, "Royal Mace of Strength", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(103, "Royal Mace of Health", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(103, "Royal Mace of Health Regen", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(100, "Cursed Royal Mace of Greater Light", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(100, "Cursed Royal Mace of Greater Darkness", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(100, "Cursed Royal Mace of Greater Magical", "Weapon", "Mace", "Any Hand", 63.5, 2.70, 12500.00, false, 5, true, "Bluntness", null, "") );
	Items.add( new ItemType(105, "Dragon Mace", "Weapon", "Mace", "Any Hand", 66.6, 2.70, 26250.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(110, "Hardened Steel Mace", "Weapon", "Mace", "Any Hand", 69.8, 2.70, 27500.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(115, "Warrior's Mace", "Weapon", "Mace", "Any Hand", 72.9, 2.70, 28750.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(120, "True Mace", "Weapon", "Mace", "Any Hand", 76.0, 2.70, 30000.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(125, "Dangle's Mace", "Weapon", "Mace", "Any Hand", 79.1, 2.70, 31250.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(130, "Moon Mace", "Weapon", "Mace", "Any Hand", 82.3, 2.70, 32500.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(135, "Soldiers's Mace", "Weapon", "Mace", "Any Hand", 85.4, 2.70, 33750.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(140, "Star Mace", "Weapon", "Mace", "Any Hand", 88.5, 2.70, 35000.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(145, "Void Mace", "Weapon", "Mace", "Any Hand", 91.6, 2.70, 36250.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(150, "Killer Mace", "Weapon", "Mace", "Any Hand", 94.8, 2.90, 37500.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(155, "Bone Mace", "Weapon", "Mace", "Any Hand", 97.9, 2.90, 38750.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(160, "Reflective Mace", "Weapon", "Mace", "Any Hand", 101.0, 2.90, 40000.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(165, "Lost Mace", "Weapon", "Mace", "Any Hand", 104.1, 2.90, 41250.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(170, "Shielded Mace", "Weapon", "Mace", "Any Hand", 107.3, 2.90, 42500.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(175, "Death Mace", "Weapon", "Mace", "Any Hand", 110.4, 2.90, 43750.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(180, "Double Hardened Mace", "Weapon", "Mace", "Any Hand", 113.5, 2.90, 45000.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(185, "Kilper's Mace", "Weapon", "Mace", "Any Hand", 116.6, 2.90, 46250.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(190, "Vorpal Mace", "Weapon", "Mace", "Any Hand", 119.8, 2.90, 47500.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(195, "General's Mace", "Weapon", "Mace", "Any Hand", 122.9, 2.90, 48750.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(200, "Grubtor's Mace", "Weapon", "Mace", "Any Hand", 126.0, 3.10, 50000.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(205, "Leech Mace", "Weapon", "Mace", "Any Hand", 129.1, 3.10, 51250.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(210, "Angel Mace", "Weapon", "Mace", "Any Hand", 132.3, 3.10, 52500.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(215, "Eagle Mace", "Weapon", "Mace", "Any Hand", 135.4, 3.10, 53750.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(220, "Noble's Mace", "Weapon", "Mace", "Any Hand", 138.5, 3.10, 55000.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(225, "Slayer's Mace", "Weapon", "Mace", "Any Hand", 141.6, 3.10, 56250.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(230, "Falcon Mace", "Weapon", "Mace", "Any Hand", 144.8, 3.10, 57500.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(235, "Forgotten Mace", "Weapon", "Mace", "Any Hand", 147.9, 3.10, 58750.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(240, "Knight's Mace", "Weapon", "Mace", "Any Hand", 151.0, 3.10, 60000.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(245, "Champion's Mace", "Weapon", "Mace", "Any Hand", 154.1, 3.10, 61250.00, false, 5, true, null, null, "") );
	Items.add( new ItemType(250, "Titanium mace", "Weapon", "Mace", "Any Hand", 157.3, 3.30, 62500.00, false, 5, true, null, null, "") );
/***************************************************************************
				Exception handling.
***************************************************************************/
}
catch(e){
	ShowException(e);
}
/***************************************************************************
	For 'Load Scripts dynamicaly with visual representation.'
***************************************************************************/
if(gLoadScript)	gLoadScript.SizeLoaded += 63378;
